name: 'Argo Rollouts Wait'
description: 'Wait for an Argo Rollout to complete with configurable timeout'
author: 'KoalaOps'

branding:
  icon: 'clock'
  color: 'purple'

inputs:
  rollout_name:
    description: 'Name of the Argo Rollout'
    required: true
  namespace:
    description: 'Kubernetes namespace'
    required: false
    default: 'default'
  timeout:
    description: 'Timeout for waiting (e.g., 300s, 5m, 10m)'
    required: false
    default: '300s'
  plugin_version:
    description: 'Argo Rollouts plugin version to install'
    required: false
    default: 'latest'

outputs:
  status:
    description: 'Final rollout status (Healthy, Degraded, Progressing, Paused)'
    value: ${{ steps.wait.outputs.status }}
  message:
    description: 'Status message from the rollout'
    value: ${{ steps.wait.outputs.message }}
  revision:
    description: 'Current revision (status.currentRevision)'
    value: ${{ steps.wait.outputs.revision }}
  updated_revision:
    description: 'Updated revision (status.updatedRevision)'
    value: ${{ steps.wait.outputs.updated_revision }}

runs:
  using: 'composite'
  steps:
    - name: Check required tools
      shell: bash
      run: |
        set -euo pipefail
        for b in kubectl jq curl; do
          command -v "$b" >/dev/null 2>&1 || { echo "::error::Missing $b"; exit 1; }
        done

    - name: Ensure Argo Rollouts plugin is installed
      shell: bash
      run: |
        set -euo pipefail
        if kubectl argo rollouts version &> /dev/null; then
          echo "âœ… Argo Rollouts plugin already installed"
          kubectl argo rollouts version
          exit 0
        fi

        echo "ðŸ“¦ Installing Argo Rollouts kubectl plugin..."
        OS=$(uname -s | tr '[:upper:]' '[:lower:]')   # linux or darwin
        ARCH=$(uname -m)
        case "$ARCH" in
          x86_64|amd64)  ARCH=amd64 ;;
          arm64|aarch64) ARCH=arm64 ;;
          *) echo "::error::Unsupported arch: $ARCH"; exit 1 ;;
        esac

        if [ "${{ inputs.plugin_version }}" = "latest" ]; then
          DOWNLOAD_URL="https://github.com/argoproj/argo-rollouts/releases/latest/download/kubectl-argo-rollouts-${OS}-${ARCH}"
        else
          DOWNLOAD_URL="https://github.com/argoproj/argo-rollouts/releases/download/${{ inputs.plugin_version }}/kubectl-argo-rollouts-${OS}-${ARCH}"
        fi

        curl -sSL -o kubectl-argo-rollouts "$DOWNLOAD_URL"
        chmod +x kubectl-argo-rollouts
        sudo mv kubectl-argo-rollouts /usr/local/bin/kubectl-argo-rollouts
        kubectl argo rollouts version
        echo "âœ… Argo Rollouts plugin installed successfully"

    - name: Verify rollout exists
      shell: bash
      run: |
        set -euo pipefail
        echo "ðŸ” Checking for rollout: ${{ inputs.rollout_name }} in namespace: ${{ inputs.namespace }}"
        if ! kubectl get rollout "${{ inputs.rollout_name }}" -n "${{ inputs.namespace }}" &> /dev/null; then
          echo "::error::Rollout not found: ${{ inputs.rollout_name }} in namespace: ${{ inputs.namespace }}"
          echo "Available rollouts in namespace:"
          kubectl get rollouts -n "${{ inputs.namespace }}" || echo "No rollouts found"
          exit 1
        fi
        echo "âœ… Rollout found"

    - name: Get initial rollout status
      shell: bash
      run: |
        echo "ðŸ“Š Initial rollout status:"
        kubectl argo rollouts get rollout "${{ inputs.rollout_name }}" \
          -n "${{ inputs.namespace }}" \
          --no-color || true

    - name: Wait for rollout
      id: wait
      shell: bash
      run: |
        set -euo pipefail
        echo "â³ Waiting for rollout to complete (timeout: ${{ inputs.timeout }})..."
        set +e
        OUTPUT=$(kubectl argo rollouts status "${{ inputs.rollout_name }}" \
          -n "${{ inputs.namespace }}" \
          --timeout "${{ inputs.timeout }}" 2>&1)
        STATUS_CODE=$?
        set -e

        echo "$OUTPUT"

        # Fetch status JSON
        ROLLOUT_JSON=$(kubectl get rollout "${{ inputs.rollout_name }}" \
          -n "${{ inputs.namespace }}" -o json)

        STATUS=$(echo "$ROLLOUT_JSON" | jq -r '.status.phase // "Unknown"')
        MESSAGE=$(echo "$ROLLOUT_JSON" | jq -r '.status.message // "No message"')
        REVISION=$(echo "$ROLLOUT_JSON" | jq -r '.status.currentRevision // "unknown"')
        UPDATED_REVISION=$(echo "$ROLLOUT_JSON" | jq -r '.status.updatedRevision // "unknown"')
        REPLICAS=$(echo "$ROLLOUT_JSON" | jq -r '.status.replicas // 0')
        READY_REPLICAS=$(echo "$ROLLOUT_JSON" | jq -r '.status.readyReplicas // 0')

        echo "status=$STATUS" >> $GITHUB_OUTPUT
        echo "message=$MESSAGE" >> $GITHUB_OUTPUT
        echo "revision=$REVISION" >> $GITHUB_OUTPUT
        echo "updated_revision=$UPDATED_REVISION" >> $GITHUB_OUTPUT

        echo "ðŸ“‹ Rollout Status:"
        echo "  Phase: $STATUS"
        echo "  Message: $MESSAGE"
        echo "  Replicas: $READY_REPLICAS/$REPLICAS ready"
        echo "  CurrentRevision: $REVISION"
        echo "  UpdatedRevision: $UPDATED_REVISION"

        if [ $STATUS_CODE -eq 0 ]; then
          echo "âœ… Rollout completed successfully"
        else
          echo "::error::Rollout failed or timed out"

          echo "::group::Rollout Details"
          kubectl argo rollouts get rollout "${{ inputs.rollout_name }}" -n "${{ inputs.namespace }}" --no-color || true
          echo "::endgroup::"

          echo "::group::Rollout History"
          kubectl argo rollouts history "${{ inputs.rollout_name }}" -n "${{ inputs.namespace }}" || true
          echo "::endgroup::"

          echo "::group::Events"
          kubectl describe rollout "${{ inputs.rollout_name }}" -n "${{ inputs.namespace }}" || true
          echo "::endgroup::"

          echo "::group::Pod Status"
          kubectl get pods -n "${{ inputs.namespace }}" \
            -l "rollouts.kubernetes.io/rollout-name=${{ inputs.rollout_name }}" \
            --show-labels || true
          echo "::endgroup::"

          exit 1
        fi

    - name: Generate summary
      if: always()
      shell: bash
      run: |
        echo "## ðŸš€ Argo Rollout Status" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Rollout:** ${{ inputs.rollout_name }}" >> $GITHUB_STEP_SUMMARY
        echo "**Namespace:** ${{ inputs.namespace }}" >> $GITHUB_STEP_SUMMARY
        echo "**Status:** ${{ steps.wait.outputs.status }}" >> $GITHUB_STEP_SUMMARY
        echo "**Message:** ${{ steps.wait.outputs.message }}" >> $GITHUB_STEP_SUMMARY
        echo "**CurrentRevision:** ${{ steps.wait.outputs.revision }}" >> $GITHUB_STEP_SUMMARY
        echo "**UpdatedRevision:** ${{ steps.wait.outputs.updated_revision }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        if [ "${{ steps.wait.outputs.status }}" = "Healthy" ]; then
          echo "âœ… Rollout is healthy" >> $GITHUB_STEP_SUMMARY
        else
          echo "âš ï¸ Rollout status: ${{ steps.wait.outputs.status }}" >> $GITHUB_STEP_SUMMARY
        fi